import pandas as pd
import streamlit as st
import plotly.express as px
from geopy.geocoders import Nominatim

# Configuration and Sidebar
st.set_page_config(layout="wide")
st.experimental_set_query_params(_sidebar="open")
DEFAULT_URL = "https://public-one.s3.us-west-2.amazonaws.com/fake_customer_data.csv"

# Data Loading
def load_data():
    uploaded_file = st.sidebar.file_uploader("Upload a CSV file", type=["csv"])
    if uploaded_file:
        df = pd.read_csv(uploaded_file)
    else:
        df = pd.read_csv(DEFAULT_URL)
    return df

# Geocoding function
def geocode(zip_code, country):
    geolocator = Nominatim(user_agent="geoapiExercises")
    location = geolocator.geocode({"postalcode": zip_code, "country": country})
    if location:
        return location.latitude, location.longitude
    else:
        return None, None

# Load offline geocoding data
geocoding_data = pd.read_csv('https://public-one.s3.us-west-2.amazonaws.com/geo-data.csv')

# Visualizations
def generate_visualizations(df):
    tab = st.sidebar.selectbox("Select a tab", ["Summary", "Numeric Data", "Categorical Data", "Geographic Data", "KPI"])

    if tab == "Summary":
        st.dataframe(df)
        with st.expander("Edit Mode"):
            edited_df = st.data_editor(data=df)
            if edited_df is not None:
                st.write("Here's the edited data:", edited_df)

    elif tab == "Numeric Data":
        numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()
        for col in numeric_cols:
            st.write(f"## {col}")
            fig = px.histogram(df, x=col)
            st.plotly_chart(fig)

    elif tab == "Categorical Data":
        categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
        for col in categorical_cols:
            st.write(f"## {col}")
            temp_df = df[col].value_counts().reset_index()
            temp_df.columns = ['value', 'count']
            fig = px.bar(temp_df, x='value', y='count')
            st.plotly_chart(fig)

    if tab == "Geographic Data":
        zip_columns = [col for col in df.columns if col.lower().replace(" ", "") in ['zip', 'zipcode', 'postalcode']]
        if zip_columns:
            zip_column = zip_columns[0]
            st.write(f"## {zip_column} Data")

            # Merge with geocoding data
            df[zip_column] = df[zip_column].astype(str)
            geo_df = pd.merge(df, geocoding_data, left_on=zip_column, right_on='Zip Code', how='left')

            # Data filtering
            filterable_cols = df.select_dtypes(include=['object']).columns.tolist()
            default_filter_index = filterable_cols.index('Customer Segment') if 'Customer Segment' in filterable_cols else 0
            filter_col = st.sidebar.selectbox("Filter by:", filterable_cols, index=default_filter_index)
            filter_value = st.sidebar.selectbox("Select value:", geo_df[filter_col].unique())
            filtered_geo_df = geo_df[geo_df[filter_col] == filter_value]

            size_col = st.sidebar.selectbox("Size by:", df.select_dtypes(include=['float64', 'int64']).columns.tolist())
            color_col = st.sidebar.selectbox("Color by:", df.select_dtypes(include=['float64', 'int64']).columns.tolist())
            
            fig = px.scatter_geo(filtered_geo_df, lat='Latitude', lon='Longitude', text=zip_column, scope='usa',
                                size=size_col, color=color_col)
            st.plotly_chart(fig, use_container_width=True)

    elif tab == "KPI":
        st.write("## Key Performance Indicators")
        
        # Data filtering for KPIs
        filterable_cols = df.select_dtypes(include=['object']).columns.tolist()
        filter_col = st.sidebar.selectbox("Filter KPIs by:", filterable_cols, index=filterable_cols.index('Customer Segment'))
        filter_val = st.sidebar.selectbox("Select value:", df[filter_col].unique())
        filtered_kpi_df = df[df[filter_col] == filter_val]
        
        # Calculating KPIs
        avg_order_value = filtered_kpi_df['Average Order Value'].mean()
        total_purchase = filtered_kpi_df['Total Purchase Amount'].sum()
        
        # Displaying KPIs
        col1, col2 = st.columns(2)
        col1.metric("Average Order Value", f"${avg_order_value:.2f}")
        col2.metric("Total Purchase Amount", f"${total_purchase:.2f}")

# Main Execution
st.title('Dynamic Data Dashboard')

# Explanation and Disclaimer
st.markdown("CSViz is a CSV data visualizer built for speed. Try your own CSV or use the sample data below to save various data visualizations.")
st.markdown("**Note**: All sample data is generated by AI and any similarities to real humans are coincidental.")

# Load data
df = load_data()
if df is not None:
    if "edited_data" not in st.session_state:
        st.session_state.edited_data = None
    
    # Tabs for mobile users
    tab_labels = ["Summary", "Numeric Data", "Categorical Data", "Geographic Data"]
    tab_choice = st.selectbox("Choose a Tab", tab_labels)
    
    # Generate visualizations based on the selected mobile tab
    generate_visualizations(df, tab=tab_choice)

    # Download Button
    csv_data = df.to_csv(index=False).encode('utf-8')
    st.download_button("Download Data as CSV", csv_data, file_name="data.csv", mime="text/csv")
